branches:
  only:
    - master
    - /^release-.*$/

language: objective-c

bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

script:
  - bundle exec fastlane ci_all
  - 'if [[ "$UPDATE_DOCUMENTATION" == "YES" ]]; then bundle exec fastlane update_docs; fi'
  # This is a workaround for a Travis-CI bug where the log might get cut-off.
  # See the [Travis-CI issue #4716](https://github.com/travis-ci/travis-ci/issues/4716).
  - sleep 3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
     # Make fastlane open the simulator before running tests. A workaround for error 65.
    - FASTLANE_EXPLICIT_OPEN_SIMULATOR=2
    - TEST_DEVICE_NAME="iPhone 6s"

matrix:
  fast_finish: true
  include:
    # Main job; builds, tests, validates the changes and updates our documentation.
    - osx_image: xcode8.3
      rvm: 2.2.5
      env: LINT=YES  RUN_TESTS=YES  BUILD_DEMO_APP=YES  RUN_UI_TESTS=YES  BUILD_LIVE_CLI=YES  UPDATE_DOCUMENTATION=YES

cache: bundler

notifications:
  email: false
